options:
  substitution_option: ALLOW_LOOSE
steps:
  - name: 'gcr.io/k8s-staging-test-infra/gcb-docker-gcloud:v20211008-60e346af'
    entrypoint: bash
    env:
      - TAG=$_GIT_TAG
      - BASE_REF=$_PULL_BASE_REF
      - REGISTRY=gcr.io/k8s-staging-ingressconformance
    args:
    - -c
    - |
      gcloud auth configure-docker \
      && make build-image publish-image
substitutions:
  _GIT_TAG: "12345"
  _PULL_BASE_REF: "master"
